# =====================================================================
# generate_xs.jl — Macroscopic multigroup cross sections + stopping
#                   powers for cppCSD, via Radiant.jl
#
# Builds electron cross-section data for one or more materials and
# writes a YAML `materials:` block matching the schema consumed by
# Parser::read() (see src/parser.h / src/parser.cpp):
#
#   materials:
#     <name>:
#       sigma_t: [...]                          # size Ng
#       sigma_s: [...]                          # size Ng
#       stopping_power:
#         group_average: [...]                  # size Ng
#         group_boundary: [...]                 # size Ng + 1
#
# sigma_t and the stopping powers are the total macroscopic
# cross-section / stopping power across all interactions below.
# sigma_s is the first (l=0, isotropic) Legendre moment of the
# in-group scattering matrix -- i.e. the diagonal of Radiant's
# combined group-to-group scattering data, dominated by large-angle
# elastic (Mott) scattering since Elastic_Collision's default angular
# Fokker-Planck decomposition already strips the small-angle part out
# into the (unused, here) momentum-transfer term.
# =====================================================================
using Radiant

# --------------------------- USER INPUT -----------------------------
# One entry per material. `name` becomes the YAML key and must match
# the material names used in the deck's `regions.materials` list.
materials_input = [
    (name = "water", density = 1.0, elements = ["H", "O"], wfractions = [0.111894, 0.888106]),
]

Ng         = 20                    # number of energy groups
E_max      = 10.0                  # midpoint energy of highest group [MeV]
E_cut      = 0.001                 # cutoff energy [MeV]
group_type = "log"                 # "log" or "linear"

legendre_order = 7                 # Legendre truncation order used internally by
                                    # Radiant's elastic-scattering decomposition;
                                    # only the l=0 moment is written out.

output_name = "materials_xs.yaml"  # output filename, written under scripts/xs_data/
# ----------------------------------------------------------------------

output_dir = joinpath(@__DIR__, "xs_data")
mkpath(output_dir)
outfile = joinpath(output_dir, output_name)

particle = Radiant.Electron()

interaction_list = [
    Radiant.Inelastic_Collision(),  # Moller collisional energy loss + catastrophic delta rays
    Radiant.Elastic_Collision(),    # Mott elastic scattering (large-angle part, AFP-decomposed)
    Radiant.Bremsstrahlung(),       # radiative energy loss
]

# --- Build materials ---
material_list = Radiant.Material[]
for m in materials_input
    @assert length(m.elements) == length(m.wfractions) "elements and wfractions must match in length for material '$(m.name)'"
    wfractions_norm = m.wfractions ./ sum(m.wfractions)

    mat = Radiant.Material(m.name)
    mat.set_density(m.density)
    for (el, f) in zip(m.elements, wfractions_norm)
        mat.add_element(el, f)
    end
    push!(material_list, mat)
end

# --- Build cross sections ---
cs = Radiant.Cross_Sections()
cs.set_source("physics-models")
cs.set_materials(material_list)
cs.set_particles([particle])
cs.set_group_structure(group_type, Ng, E_max, E_cut)
cs.set_interactions(interaction_list)
cs.set_legendre_order(legendre_order)
cs.build()

# --- Pull data ---
# Radiant numbers groups from the highest energy down to the lowest (group 1
# = E_max), but Parser::read requires a strictly ascending energy_mesh, so
# every per-group quantity below is reversed to match.
Eb = reverse(cs.get_energy_boundaries(particle))                 # MeV, size Ng+1, ascending
Σt = cs.get_total(particle)                                      # [Ng, Nmat], cm^-1
Σs_moments = cs.get_scattering(particle, particle, legendre_order) # [Nmat, Ng, Ng, legendre_order+1]
S  = cs.get_stopping_powers(particle)                             # [Ng, Nmat], MeV/cm
Sb = cs.get_boundary_stopping_powers(particle)                    # [Ng+1, Nmat], MeV/cm

# --- Write YAML ---
format_vector(v) = "[" * join(v, ", ") * "]"

open(outfile, "w") do io
    println(io, "# Generated by scripts/generate_xs.jl (Radiant.jl)")
    println(io, "# Particle: electron")
    println(io, "# Group structure: ", group_type, ", Ng=", Ng,
                 ", E_max=", E_max, " MeV, E_cut=", E_cut, " MeV")
    println(io, "#")
    println(io, "energy_mesh: ", format_vector(Eb))
    println(io)
    println(io, "materials:")
    for (imat, m) in enumerate(materials_input)
        sigma_t = reverse(Σt[:, imat])
        sigma_s = reverse([Σs_moments[imat, g, g, 1] for g in 1:Ng])
        stopping_power_average = reverse(S[:, imat])
        stopping_power_boundary = reverse(Sb[:, imat])

        println(io, "  ", m.name, ":")
        println(io, "    sigma_t: ", format_vector(sigma_t))
        println(io, "    sigma_s: ", format_vector(sigma_s))
        println(io, "    stopping_power:")
        println(io, "      group_average: ", format_vector(stopping_power_average))
        println(io, "      group_boundary: ", format_vector(stopping_power_boundary))
    end
end

println("Wrote cross sections for $(length(materials_input)) material(s) to $outfile")
